name: Run Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Every day at 3:00am
    - cron: '0 3 * * *'
        

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install PyTorch
      run: |
        python -m pip install --upgrade pip
        # Install CPU-based pytorch
        pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        # Maybe use the CUDA 10.2 version instead?
        # pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
        pip install -r requirements.txt
    - name: Run Test
      run: |
        python -m main play --agents amy_santiago --train 1 --n-round 25 --no-gui
    - name: Open issue on failure
      if: ${{ failure() && github.event_name  == 'schedule' }}
      uses: rishabhgupta/git-action-issue@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Daily CI failed
        body:  Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed, please check why
        assignees: ''
  train-model:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install PyTorch
      run: |
        python -m pip install --upgrade pip
        pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        pip install -r requirements.txt
    - name: Run Train
      run: |
        python -m main play --agents amy_santiago --train 1 --n-round 25 --no-gui
